---

- hosts: localhost
  connection: local
  roles:
    - role: k3s/local
      become: true

- hosts: master
  roles:
    - role: k3s/master
      become: true

- hosts: localhost
  connection: local
  roles:
    - role: k3s/local2
      become: true

- hosts: node
  connection: local
  roles:
    - role: k3s/node
      become: true

- hosts: k3s_cluster
  roles:
    - role: k3s/post
      become: true


