---
#- name: Disable services
#  systemd:
#    name: "{{ item }}"
#    state: stopped
#    enabled: no
#  failed_when: false
#  with_items:
#    - k3s
#    - k3s-node
#    - k3s-init
#
#- name: RUN pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
#  register: pkill_containerd_shim_runc
#  command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
#  changed_when: "pkill_containerd_shim_runc.rc == 0"
#  failed_when: false

- name: Uninstall K3s
  become: true
  command: sh /usr/local/bin/k3s-uninstall.sh

- name: Clean up Rancher and Kubeconfig
  ansible.builtin.shell:
    cmd: "rm -rf /var/lib/rancher /etc/rancher ~/.kube/*; ip addr flush dev lo; ip addr add 127.0.0.1/8 dev lo;"

- name: Umount k3s filesystems
  include_tasks: umount_with_children.yml
  with_items:
    - /run/k3s
    - /var/lib/kubelet
    - /run/netns
    - /var/lib/rancher/k3s
    - /var/lib/kubelet/pods
    - /var/lib/kubelet/plugins
    - /run/netns/cni-
  loop_control:
    loop_var: mounted_fs


- name: Remove service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - "{{ systemd_dir }}/k3s.service"
    - "{{ systemd_dir }}/k3s-node.service"
    - /etc/rancher/k3s
    - /run/k3s
    - /run/flannel
    - /etc/rancher/
    - /var/lib/kubelet
    - /var/lib/rancher/k3s
    - /var/lib/rancher/
    - /var/lib/cni/
    - "{{ ansible_user_dir }}/.kube/config"
    - /usr/local/bin/kubectl
    - /usr/local/bin/crictl
    - /usr/local/bin/ctr

- name: Reload daemon_reload
  systemd:
    daemon_reload: yes

- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent

#- name: Check if rc.local exists
#  stat:
#    path: /etc/rc.local
#  register: rcfile
